In [1]:
import pandas as pd

In [2]:
foods = pd.read_csv("foods.csv")
foods.head(5)

  First Name  Gender          City Frequency       Item  Spend
0      Wanda  Female      Stamford    Weekly     Burger  15.66
1       Eric    Male      Stamford     Daily    Chalupa  10.56
2    Charles    Male      New York     Never      Sushi  42.14
3       Anna  Female  Philadelphia      Once  Ice Cream  11.01
4    Deborah  Female  Philadelphia     Daily    Chalupa  23.49

In [3]:
foods

    First Name  Gender          City Frequency       Item  Spend
0        Wanda  Female      Stamford    Weekly     Burger  15.66
1         Eric    Male      Stamford     Daily    Chalupa  10.56
2      Charles    Male      New York     Never      Sushi  42.14
3         Anna  Female  Philadelphia      Once  Ice Cream  11.01
4      Deborah  Female  Philadelphia     Daily    Chalupa  23.49
..         ...     ...           ...       ...        ...    ...
995      Donna  Female      New York   Monthly      Sushi  83.53
996     Albert    Male  Philadelphia     Daily      Sushi  72.88
997       Jean  Female      Stamford    Weekly      Donut   5.85
998    Jessica  Female      New York     Daily    Chalupa  43.19
999      Brian    Male      New York     Daily    Chalupa  28.36

[1000 rows x 6 columns]

In [4]:
foods.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  1000 non-null   str
 1   Gender      1000 non-null   str
 2   City        1000 non-null   str
 3   Frequency   1000 non-null   str
 4   Item        1000 non-null   str
 5   Spend       1000 non-null   float64
dtypes: float64(1), str(5)
memory usage: 47.0 KB

In [5]:
foods.isnull().sum()

First Name    0
Gender        0
City          0
Frequency     0
Item          0
Spend         0
dtype: int64

In [6]:
# Since there are no null values,so checking for duplicate rows
foods.duplicated().sum()

np.int64(0)

In [7]:
# Inspect each categorical column for inconsistent values
foods['Gender'].value_counts()

Gender
Female    512
Male      488
Name: count, dtype: int64

In [8]:
foods['City'].value_counts()

City
Philadelphia    359
Stamford        328
New York        313
Name: count, dtype: int64

In [9]:
foods['Frequency'].value_counts()

Frequency
Weekly     145
Daily      137
Once       132
Yearly     126
Often      125
Never      120
Monthly    111
Seldom     104
Name: count, dtype: int64

In [10]:
foods['Item'].value_counts()

Item
Donut        187
Ice Cream    176
Burrito      168
Sushi        166
Burger       156
Chalupa      147
Name: count, dtype: int64

In [11]:
# Checking the Spend column
foods['Spend'].describe()

count    1000.000000
mean       50.069370
std        27.728471
min         1.020000
25%        27.380000
50%        48.825000
75%        73.092500
max        99.870000
Name: Spend, dtype: float64

In [12]:
# removing the hidden spaces 
foods["First Name"] = foods["First Name"].str.strip()
foods["Gender"] = foods["Gender"].str.strip()
foods["City"] = foods["City"].str.strip()
foods["Frequency"] = foods["Frequency"].str.strip()
foods["Item"] = foods["Item"].str.strip()

In [13]:
foods.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  1000 non-null   str
 1   Gender      1000 non-null   str
 2   City        1000 non-null   str
 3   Frequency   1000 non-null   str
 4   Item        1000 non-null   str
 5   Spend       1000 non-null   float64
dtypes: float64(1), str(5)
memory usage: 47.0 KB

In [14]:
foods.to_csv("foods_clean.csv", index = False)

In [15]:
foods

    First Name  Gender          City Frequency       Item  Spend
0        Wanda  Female      Stamford    Weekly     Burger  15.66
1         Eric    Male      Stamford     Daily    Chalupa  10.56
2      Charles    Male      New York     Never      Sushi  42.14
3         Anna  Female  Philadelphia      Once  Ice Cream  11.01
4      Deborah  Female  Philadelphia     Daily    Chalupa  23.49
..         ...     ...           ...       ...        ...    ...
995      Donna  Female      New York   Monthly      Sushi  83.53
996     Albert    Male  Philadelphia     Daily      Sushi  72.88
997       Jean  Female      Stamford    Weekly      Donut   5.85
998    Jessica  Female      New York     Daily    Chalupa  43.19
999      Brian    Male      New York     Daily    Chalupa  28.36

[1000 rows x 6 columns]


# Pandas Comprehensive
- Text Data

In [16]:
foods.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  1000 non-null   str
 1   Gender      1000 non-null   str
 2   City        1000 non-null   str
 3   Frequency   1000 non-null   str
 4   Item        1000 non-null   str
 5   Spend       1000 non-null   float64
dtypes: float64(1), str(5)
memory usage: 47.0 KB

In [17]:
foods["Gender"]

0      Female
1        Male
2        Male
3      Female
4      Female
        ...
995    Female
996      Male
997    Female
998    Female
999      Male
Name: Gender, Length: 1000, dtype: str

In [18]:
foods["Gender"] = foods["Gender"].astype("category")

In [19]:
foods["Gender"].dtypes

CategoricalDtype(categories=['Female', 'Male'], ordered=False, categories_dtype=str)

In [20]:
foods["City"] = foods["City"].astype("category")

In [21]:
foods["City"].dtypes

CategoricalDtype(categories=['New York', 'Philadelphia', 'Stamford'], ordered=False, categories_dtype=str)

In [22]:
foods.axes

[RangeIndex(start=0, stop=1000, step=1),
 Index(['First Name', 'Gender', 'City', 'Frequency', 'Item', 'Spend'], dtype='str')]

In [23]:
foods

    First Name  Gender          City Frequency       Item  Spend
0        Wanda  Female      Stamford    Weekly     Burger  15.66
1         Eric    Male      Stamford     Daily    Chalupa  10.56
2      Charles    Male      New York     Never      Sushi  42.14
3         Anna  Female  Philadelphia      Once  Ice Cream  11.01
4      Deborah  Female  Philadelphia     Daily    Chalupa  23.49
..         ...     ...           ...       ...        ...    ...
995      Donna  Female      New York   Monthly      Sushi  83.53
996     Albert    Male  Philadelphia     Daily      Sushi  72.88
997       Jean  Female      Stamford    Weekly      Donut   5.85
998    Jessica  Female      New York     Daily    Chalupa  43.19
999      Brian    Male      New York     Daily    Chalupa  28.36

[1000 rows x 6 columns]

In [24]:
foods["First Name"].str.lower().head()

0      wanda
1       eric
2    charles
3       anna
4    deborah
Name: First Name, dtype: str

In [25]:
foods["City"].str.upper().head()

0        STAMFORD
1        STAMFORD
2        NEW YORK
3    PHILADELPHIA
4    PHILADELPHIA
Name: City, dtype: object

In [26]:
foods["First Name"].str.lower().str.title().head()

0      Wanda
1       Eric
2    Charles
3       Anna
4    Deborah
Name: First Name, dtype: str

In [27]:
foods["Item"].str.len().head()

0    6
1    7
2    5
3    9
4    7
Name: Item, dtype: int64

In [28]:
foods["Frequency"].value_counts()

Frequency
Weekly     145
Daily      137
Once       132
Yearly     126
Often      125
Never      120
Monthly    111
Seldom     104
Name: count, dtype: int64

In [29]:
# inserting spaces before and after the frequency value to see the changes of strip method
foods["Frequency_with_space"] = foods["Frequency"].map({
    "Weekly" : "   Weekly   ",
    "Daily" : "   Daily  ",
    "Once" : "  Once ",
    "Yearly" : "  Yearly  ",
    "Often" : "Often  ",
    "Never" : " Never",
    "Monthly" : "  Monthly",
    "Seldom" : " Seldom " 
})

In [30]:
foods

,First Name,Gender,City,Frequency,Item,Spend,Frequency_with_space
0,Wanda,Female,Stamford,Weekly,Burger,15.66,Weekly
1,Eric,Male,Stamford,Daily,Chalupa,10.56,Daily
2,Charles,Male,New York,Never,Sushi,42.14,Never
3,Anna,Female,Philadelphia,Once,Ice Cream,11.01,Once
4,Deborah,Female,Philadelphia,Daily,Chalupa,23.49,Daily
...,...,...,...,...,...,...,...
995,Donna,Female,New York,Monthly,Sushi,83.53,Monthly
996,Albert,Male,Philadelphia,Daily,Sushi,72.88,Daily
997,Jean,Female,Stamford,Weekly,Donut,5.85,Weekly
998,Jessica,Female,New York,Daily,Chalupa,43.19,Daily
999,Brian,Male,New York,Daily,Chalupa,28.36,Daily

In [31]:
foods["Frequency_with_space"][0]

'   Weekly   '

In [32]:
foods["Frequency_with_space"] = foods["Frequency_with_space"].str.strip()

In [33]:
foods["Frequency_with_space"]

0       Weekly
1        Daily
2        Never
3         Once
4        Daily
        ...
995    Monthly
996      Daily
997     Weekly
998      Daily
999      Daily
Name: Frequency_with_space, Length: 1000, dtype: str

In [34]:
foods

,First Name,Gender,City,Frequency,Item,Spend,Frequency_with_space
0,Wanda,Female,Stamford,Weekly,Burger,15.66,Weekly
1,Eric,Male,Stamford,Daily,Chalupa,10.56,Daily
2,Charles,Male,New York,Never,Sushi,42.14,Never
3,Anna,Female,Philadelphia,Once,Ice Cream,11.01,Once
4,Deborah,Female,Philadelphia,Daily,Chalupa,23.49,Daily
...,...,...,...,...,...,...,...
995,Donna,Female,New York,Monthly,Sushi,83.53,Monthly
996,Albert,Male,Philadelphia,Daily,Sushi,72.88,Daily
997,Jean,Female,Stamford,Weekly,Donut,5.85,Weekly
998,Jessica,Female,New York,Daily,Chalupa,43.19,Daily
999,Brian,Male,New York,Daily,Chalupa,28.36,Daily

In [35]:
foods["Frequency_with_space"][0]

'Weekly'

In [36]:
foods = foods.drop(columns = "Frequency_with_space")

In [37]:
foods

    First Name  Gender          City Frequency       Item  Spend
0        Wanda  Female      Stamford    Weekly     Burger  15.66
1         Eric    Male      Stamford     Daily    Chalupa  10.56
2      Charles    Male      New York     Never      Sushi  42.14
3         Anna  Female  Philadelphia      Once  Ice Cream  11.01
4      Deborah  Female  Philadelphia     Daily    Chalupa  23.49
..         ...     ...           ...       ...        ...    ...
995      Donna  Female      New York   Monthly      Sushi  83.53
996     Albert    Male  Philadelphia     Daily      Sushi  72.88
997       Jean  Female      Stamford    Weekly      Donut   5.85
998    Jessica  Female      New York     Daily    Chalupa  43.19
999      Brian    Male      New York     Daily    Chalupa  28.36

[1000 rows x 6 columns]

In [38]:
foods = pd.read_csv("foods.csv")

In [39]:
foods["Gender"] = foods["Gender"].str.replace("Female", "F")

In [40]:
foods["Gender"] = foods["Gender"].str.replace("Male", "M")

In [41]:
foods["Gender"]

0      F
1      M
2      M
3      F
4      F
      ..
995    F
996    M
997    F
998    F
999    M
Name: Gender, Length: 1000, dtype: str

In [42]:
foods["Spend"].min()

np.float64(1.02)

In [43]:
foods["Spend"].max()

np.float64(99.87)

In [44]:
foods["Spend"].mean()

np.float64(50.06936999999999)

In [45]:
foods["Spend"].median()

np.float64(48.825)

In [46]:
foods["Spend"].std()

np.float64(27.728471144567546)

In [47]:
# people who spends weekly
weekly_spending_people = foods["Frequency"].str.lower().str.contains("weekly")
foods[weekly_spending_people]

    First Name Gender          City Frequency       Item  Spend
0        Wanda      F      Stamford    Weekly     Burger  15.66
17     Frances      F      New York    Weekly    Chalupa   3.54
21        Rose      F      New York    Weekly      Sushi  40.76
27   Stephanie      F      New York    Weekly  Ice Cream  77.70
30        Rose      F  Philadelphia    Weekly      Sushi  59.27
..         ...    ...           ...       ...        ...    ...
956    Frances      F  Philadelphia    Weekly      Donut  95.32
974    Antonio      M  Philadelphia    Weekly    Burrito  40.01
978    Charles      M      Stamford    Weekly      Donut  64.28
985     Ernest      M      New York    Weekly    Burrito  70.17
997       Jean      F      Stamford    Weekly      Donut   5.85

[145 rows x 6 columns]

In [48]:
# filtering females
females_mask = foods["Gender"].str.lower().str.contains("f")
foods[females_mask]

    First Name Gender          City Frequency       Item  Spend
0        Wanda      F      Stamford    Weekly     Burger  15.66
3         Anna      F  Philadelphia      Once  Ice Cream  11.01
4      Deborah      F  Philadelphia     Daily    Chalupa  23.49
11      Rachel      F  Philadelphia    Seldom      Sushi  71.68
12        Mary      F  Philadelphia      Once     Burger   1.97
..         ...    ...           ...       ...        ...    ...
990     Pamela      F      New York     Never     Burger  97.89
994    Shirley      F      Stamford     Never    Burrito  98.61
995      Donna      F      New York   Monthly      Sushi  83.53
997       Jean      F      Stamford    Weekly      Donut   5.85
998    Jessica      F      New York     Daily    Chalupa  43.19

[512 rows x 6 columns]

In [49]:
# no of females
foods[females_mask].shape

(512, 6)

In [50]:
# filtering people staying in Philadelphia
Philadelphia_inhabitants = foods["City"].str.lower().str.startswith("p")
foods[Philadelphia_inhabitants]

    First Name Gender          City Frequency       Item  Spend
3         Anna      F  Philadelphia      Once  Ice Cream  11.01
4      Deborah      F  Philadelphia     Daily    Chalupa  23.49
6         Mark      M  Philadelphia   Monthly  Ice Cream  30.01
7         Paul      M  Philadelphia   Monthly    Chalupa  17.65
11      Rachel      F  Philadelphia    Seldom      Sushi  71.68
..         ...    ...           ...       ...        ...    ...
974    Antonio      M  Philadelphia    Weekly    Burrito  40.01
976      Jesse      M  Philadelphia     Never  Ice Cream  95.69
982    Jeffrey      M  Philadelphia      Once     Burger  35.88
993       Mark      M  Philadelphia    Seldom      Donut  13.79
996     Albert      M  Philadelphia     Daily      Sushi  72.88

[359 rows x 6 columns]

In [51]:
foods[Philadelphia_inhabitants].shape

(359, 6)

In [52]:
foods["Item"].value_counts()

Item
Donut        187
Ice Cream    176
Burrito      168
Sushi        166
Burger       156
Chalupa      147
Name: count, dtype: int64

In [53]:
# filtering people love to eat icecream
ice_cream_consumers = foods["Item"].str.lower().str.endswith("cream")
foods[ice_cream_consumers]

    First Name Gender          City Frequency       Item  Spend
3         Anna      F  Philadelphia      Once  Ice Cream  11.01
6         Mark      M  Philadelphia   Monthly  Ice Cream  30.01
10      Samuel      M      Stamford     Daily  Ice Cream  15.17
15        Paul      M  Philadelphia     Often  Ice Cream  97.67
18       Bruce      M      Stamford     Often  Ice Cream  99.17
..         ...    ...           ...       ...        ...    ...
967       Carl      M  Philadelphia      Once  Ice Cream  47.13
972      Wayne      M      Stamford      Once  Ice Cream  14.13
976      Jesse      M  Philadelphia     Never  Ice Cream  95.69
984      Jimmy      M      Stamford     Never  Ice Cream  35.74
991    Anthony      M      Stamford    Yearly  Ice Cream   8.72

[176 rows x 6 columns]

In [54]:
foods = pd.read_csv("foods.csv", index_col = "First Name")

In [55]:
foods

            Gender          City Frequency       Item  Spend
First Name
Wanda       Female      Stamford    Weekly     Burger  15.66
Eric          Male      Stamford     Daily    Chalupa  10.56
Charles       Male      New York     Never      Sushi  42.14
Anna        Female  Philadelphia      Once  Ice Cream  11.01
Deborah     Female  Philadelphia     Daily    Chalupa  23.49
...            ...           ...       ...        ...    ...
Donna       Female      New York   Monthly      Sushi  83.53
Albert        Male  Philadelphia     Daily      Sushi  72.88
Jean        Female      Stamford    Weekly      Donut   5.85
Jessica     Female      New York     Daily    Chalupa  43.19
Brian         Male      New York     Daily    Chalupa  28.36

[1000 rows x 5 columns]

In [56]:
foods.index = foods.index.str.strip().str.upper().sort_values()
foods.head()

            Gender          City Frequency       Item  Spend
First Name
AARON       Female      Stamford    Weekly     Burger  15.66
AARON         Male      Stamford     Daily    Chalupa  10.56
AARON         Male      New York     Never      Sushi  42.14
AARON       Female  Philadelphia      Once  Ice Cream  11.01
ADAM        Female  Philadelphia     Daily    Chalupa  23.49

In [57]:
foods.columns = foods.columns.str.upper()
foods.head()

            GENDER          CITY FREQUENCY       ITEM  SPEND
First Name
AARON       Female      Stamford    Weekly     Burger  15.66
AARON         Male      Stamford     Daily    Chalupa  10.56
AARON         Male      New York     Never      Sushi  42.14
AARON       Female  Philadelphia      Once  Ice Cream  11.01
ADAM        Female  Philadelphia     Daily    Chalupa  23.49

In [58]:
foods.columns = foods.columns.str.title()
foods.head()

            Gender          City Frequency       Item  Spend
First Name
AARON       Female      Stamford    Weekly     Burger  15.66
AARON         Male      Stamford     Daily    Chalupa  10.56
AARON         Male      New York     Never      Sushi  42.14
AARON       Female  Philadelphia      Once  Ice Cream  11.01
ADAM        Female  Philadelphia     Daily    Chalupa  23.49

In [3]:
import pandas as pd
foods = pd.read_csv("foods.csv")

In [63]:
foods['Frequency_Item'] = foods["Frequency"] + " " + foods["Item"]
foods['Frequency_Item']

0       Weekly Burger
1       Daily Chalupa
2         Never Sushi
3      Once Ice Cream
4       Daily Chalupa
            ...
995     Monthly Sushi
996       Daily Sushi
997      Weekly Donut
998     Daily Chalupa
999     Daily Chalupa
Name: Frequency_Item, Length: 1000, dtype: str

In [64]:
foods.head(2)

  First Name  Gender      City Frequency     Item  Spend Frequency_Item
0      Wanda  Female  Stamford    Weekly   Burger  15.66  Weekly Burger
1       Eric    Male  Stamford     Daily  Chalupa  10.56  Daily Chalupa

In [72]:
foods["Frequency_Item"].str.split(" ").str.get(0).value_counts().head()

Frequency_Item
Weekly    145
Daily     137
Once      132
Yearly    126
Often     125
Name: count, dtype: int64

In [73]:
foods["Frequency_From_Item"] = foods["Frequency_Item"].str.split(" ").str.get(0)

In [74]:
foods["Frequency_From_Item"]

0       Weekly
1        Daily
2        Never
3         Once
4        Daily
        ...
995    Monthly
996      Daily
997     Weekly
998      Daily
999      Daily
Name: Frequency_From_Item, Length: 1000, dtype: object

In [75]:
foods

,First Name,Gender,City,Frequency,Item,Spend,Frequency_Item,Frequency_From_Item
0,Wanda,Female,Stamford,Weekly,Burger,15.66,Weekly Burger,Weekly
1,Eric,Male,Stamford,Daily,Chalupa,10.56,Daily Chalupa,Daily
2,Charles,Male,New York,Never,Sushi,42.14,Never Sushi,Never
3,Anna,Female,Philadelphia,Once,Ice Cream,11.01,Once Ice Cream,Once
4,Deborah,Female,Philadelphia,Daily,Chalupa,23.49,Daily Chalupa,Daily
...,...,...,...,...,...,...,...,...
995,Donna,Female,New York,Monthly,Sushi,83.53,Monthly Sushi,Monthly
996,Albert,Male,Philadelphia,Daily,Sushi,72.88,Daily Sushi,Daily
997,Jean,Female,Stamford,Weekly,Donut,5.85,Weekly Donut,Weekly
998,Jessica,Female,New York,Daily,Chalupa,43.19,Daily Chalupa,Daily
999,Brian,Male,New York,Daily,Chalupa,28.36,Daily Chalupa,Daily

In [81]:
# using limit n = 1 so that the ice cream kind of data can be handled 

foods[["frequency_ex_split", "item_ex_split"]] = foods["Frequency_Item"].str.split(" ", expand = True, n=1)
foods.head()

,First Name,Gender,City,Frequency,Item,Spend,Frequency_Item,Frequency_From_Item,frequency_ex_split,item_ex_split
0,Wanda,Female,Stamford,Weekly,Burger,15.66,Weekly Burger,Weekly,Weekly,Burger
1,Eric,Male,Stamford,Daily,Chalupa,10.56,Daily Chalupa,Daily,Daily,Chalupa
2,Charles,Male,New York,Never,Sushi,42.14,Never Sushi,Never,Never,Sushi
3,Anna,Female,Philadelphia,Once,Ice Cream,11.01,Once Ice Cream,Once,Once,Ice Cream
4,Deborah,Female,Philadelphia,Daily,Chalupa,23.49,Daily Chalupa,Daily,Daily,Chalupa

In [4]:
# find the most common item
foods["Item"].str.lower().value_counts()

Item
donut        187
ice cream    176
burrito      168
sushi        166
burger       156
chalupa      147
Name: count, dtype: int64

In [60]:
multi_foods = foods.set_index(['City','Gender'])

In [136]:
multi_foods

                    First Name Frequency       Item  Spend
City         Gender
Stamford     Female      Wanda    Weekly     Burger  15.66
             Male         Eric     Daily    Chalupa  10.56
New York     Male      Charles     Never      Sushi  42.14
Philadelphia Female       Anna      Once  Ice Cream  11.01
             Female    Deborah     Daily    Chalupa  23.49
...                        ...       ...        ...    ...
New York     Female      Donna   Monthly      Sushi  83.53
Philadelphia Male       Albert     Daily      Sushi  72.88
Stamford     Female       Jean    Weekly      Donut   5.85
New York     Female    Jessica     Daily    Chalupa  43.19
             Male        Brian     Daily    Chalupa  28.36

[1000 rows x 4 columns]

In [72]:
# new df to exercise multiindex
employees = pd.read_csv("employees.csv")

In [49]:
employees

     Department                Role  Base_Salary  Bonus
0   Engineering    Backend Engineer       115000  12000
1   Engineering   Frontend Engineer       105000  10000
2   Engineering     DevOps Engineer       120000  14000
3   Engineering         QA Engineer        90000   8000
4          Data      Data Scientist       125000  15000
5          Data        Data Analyst        85000   7500
6          Data       Data Engineer       118000  13000
7     Marketing      SEO Specialist        70000   5000
8     Marketing  Content Strategist        75000   6000
9     Marketing     Growth Marketer        95000   9000
10        Sales   Account Executive        80000  25000
11        Sales       Sales Manager       110000  30000

In [73]:
multi_emp = employees.set_index(['Department', 'Role'])

In [74]:
multi_emp

                                Base_Salary  Bonus
Department  Role
Engineering Backend Engineer         115000  12000
            Frontend Engineer        105000  10000
            DevOps Engineer          120000  14000
            QA Engineer               90000   8000
Data        Data Scientist           125000  15000
            Data Analyst              85000   7500
            Data Engineer            118000  13000
Marketing   SEO Specialist            70000   5000
            Content Strategist        75000   6000
            Growth Marketer           95000   9000
Sales       Account Executive         80000  25000
            Sales Manager            110000  30000

In [52]:
multi_emp.loc["Engineering"]

                   Base_Salary  Bonus
Role
Backend Engineer        115000  12000
Frontend Engineer       105000  10000
DevOps Engineer         120000  14000
QA Engineer              90000   8000

In [53]:
multi_emp.loc[("Engineering","Backend Engineer")]

Base_Salary    115000
Bonus           12000
Name: (Engineering, Backend Engineer), dtype: int64

In [54]:
multi_emp.loc[("Engineering", "Backend Engineer"), "Bonus"]

np.int64(12000)

In [55]:
multi_emp.loc[["Engineering", "Sales"]]

                               Base_Salary  Bonus
Department  Role
Engineering Backend Engineer        115000  12000
            Frontend Engineer       105000  10000
            DevOps Engineer         120000  14000
            QA Engineer              90000   8000
Sales       Account Executive        80000  25000
            Sales Manager           110000  30000

In [56]:
multi_emp.iloc[0, 0]

np.int64(115000)

In [75]:
multi_emp

                                Base_Salary  Bonus
Department  Role
Engineering Backend Engineer         115000  12000
            Frontend Engineer        105000  10000
            DevOps Engineer          120000  14000
            QA Engineer               90000   8000
Data        Data Scientist           125000  15000
            Data Analyst              85000   7500
            Data Engineer            118000  13000
Marketing   SEO Specialist            70000   5000
            Content Strategist        75000   6000
            Growth Marketer           95000   9000
Sales       Account Executive         80000  25000
            Sales Manager            110000  30000

In [76]:
multi_emp.unstack()

                  Base_Salary                                      \
Role        Account Executive Backend Engineer Content Strategist
Department
Data                      NaN              NaN                NaN
Engineering               NaN         115000.0                NaN
Marketing                 NaN              NaN            75000.0
Sales                 80000.0              NaN                NaN

                                                                       \
Role        Data Analyst Data Engineer Data Scientist DevOps Engineer
Department
Data             85000.0      118000.0       125000.0             NaN
Engineering          NaN           NaN            NaN        120000.0
Marketing            NaN           NaN            NaN             NaN
Sales                NaN           NaN            NaN             NaN

                                                           ...  \
Role        Frontend Engineer Growth Marketer QA Engineer  ...
Department                                                 ...
Data                      NaN             NaN         NaN  ...
Engineering          105000.0             NaN     90000.0  ...
Marketing                 NaN         95000.0         NaN  ...
Sales                     NaN             NaN         NaN  ...

                         Bonus                                            \
Role        Content Strategist Data Analyst Data Engineer Data Scientist
Department
Data                       NaN       7500.0       13000.0        15000.0
Engineering                NaN          NaN           NaN            NaN
Marketing               6000.0          NaN           NaN            NaN
Sales                      NaN          NaN           NaN            NaN

                                                                           \
Role        DevOps Engineer Frontend Engineer Growth Marketer QA Engineer
Department
Data                    NaN               NaN             NaN         NaN
Engineering         14000.0           10000.0             NaN      8000.0
Marketing               NaN               NaN          9000.0         NaN
Sales                   NaN               NaN             NaN         NaN


Role        SEO Specialist Sales Manager
Department
Data                   NaN           NaN
Engineering            NaN           NaN
Marketing           5000.0           NaN
Sales                  NaN       30000.0

[4 rows x 24 columns]

In [77]:
multi_emp = multi_emp.unstack(level = "Role")
multi_emp

                  Base_Salary                                      \
Role        Account Executive Backend Engineer Content Strategist
Department
Data                      NaN              NaN                NaN
Engineering               NaN         115000.0                NaN
Marketing                 NaN              NaN            75000.0
Sales                 80000.0              NaN                NaN

                                                                       \
Role        Data Analyst Data Engineer Data Scientist DevOps Engineer
Department
Data             85000.0      118000.0       125000.0             NaN
Engineering          NaN           NaN            NaN        120000.0
Marketing            NaN           NaN            NaN             NaN
Sales                NaN           NaN            NaN             NaN

                                                           ...  \
Role        Frontend Engineer Growth Marketer QA Engineer  ...
Department                                                 ...
Data                      NaN             NaN         NaN  ...
Engineering          105000.0             NaN     90000.0  ...
Marketing                 NaN         95000.0         NaN  ...
Sales                     NaN             NaN         NaN  ...

                         Bonus                                            \
Role        Content Strategist Data Analyst Data Engineer Data Scientist
Department
Data                       NaN       7500.0       13000.0        15000.0
Engineering                NaN          NaN           NaN            NaN
Marketing               6000.0          NaN           NaN            NaN
Sales                      NaN          NaN           NaN            NaN

                                                                           \
Role        DevOps Engineer Frontend Engineer Growth Marketer QA Engineer
Department
Data                    NaN               NaN             NaN         NaN
Engineering         14000.0           10000.0             NaN      8000.0
Marketing               NaN               NaN          9000.0         NaN
Sales                   NaN               NaN             NaN         NaN


Role        SEO Specialist Sales Manager
Department
Data                   NaN           NaN
Engineering            NaN           NaN
Marketing           5000.0           NaN
Sales                  NaN       30000.0

[4 rows x 24 columns]

In [79]:
multi_emp = multi_emp.stack()

In [81]:
multi_emp.dropna(how = "any")

                                Base_Salary    Bonus
Department  Role
Data        Data Analyst            85000.0   7500.0
            Data Engineer          118000.0  13000.0
            Data Scientist         125000.0  15000.0
Engineering Backend Engineer       115000.0  12000.0
            DevOps Engineer        120000.0  14000.0
            Frontend Engineer      105000.0  10000.0
            QA Engineer             90000.0   8000.0
Marketing   Content Strategist      75000.0   6000.0
            Growth Marketer         95000.0   9000.0
            SEO Specialist          70000.0   5000.0
Sales       Account Executive       80000.0  25000.0
            Sales Manager          110000.0  30000.0

# Merging dataframes

In [89]:
import numpy as np
# Create sample dataframes for merging
students = pd.DataFrame({
    'StudentID': [101, 102, 103, 104, 105, 106],
    'Name': ['John', 'Jane', 'Bob', 'Alice', 'Charlie', 'Henry'],
    'SubjectID': [1, 2, 1, 3, 2, np.nan]
})

subjects = pd.DataFrame({
    'SubjectID': [1, 2, 3, 4],
    'SubName': ['AI', 'OS', 'TOC', 'DBMS'],
    
})

marks = pd.DataFrame({
    'StudentID': [101, 102, 103, 104, 105,106],
    'marks': [60, 75, 55, 80, 70,80],
})

print("Students:")
print(students)
print("\nSubjects:")
print(subjects)
print("\nMarks:")
print(marks)

Students:
   StudentID     Name  SubjectID
0        101     John        1.0
1        102     Jane        2.0
2        103      Bob        1.0
3        104    Alice        3.0
4        105  Charlie        2.0
5        106    Henry        NaN

Subjects:
   SubjectID SubName
0          1      AI
1          2      OS
2          3     TOC
3          4    DBMS

Marks:
   StudentID  marks
0        101     60
1        102     75
2        103     55
3        104     80
4        105     70
5        106     80

In [90]:
inner_join = pd.merge(students, subjects, on='SubjectID', how='inner')
inner_join

   StudentID     Name  SubjectID SubName
0        101     John        1.0      AI
1        102     Jane        2.0      OS
2        103      Bob        1.0      AI
3        104    Alice        3.0     TOC
4        105  Charlie        2.0      OS

In [92]:
left_join = pd.merge(students, subjects, on='SubjectID', how='left')
left_join

   StudentID     Name  SubjectID SubName
0        101     John        1.0      AI
1        102     Jane        2.0      OS
2        103      Bob        1.0      AI
3        104    Alice        3.0     TOC
4        105  Charlie        2.0      OS
5        106    Henry        NaN     NaN

In [93]:
right_join = pd.merge(students, subjects, on='SubjectID', how='right')
right_join

   StudentID     Name  SubjectID SubName
0      101.0     John        1.0      AI
1      103.0      Bob        1.0      AI
2      102.0     Jane        2.0      OS
3      105.0  Charlie        2.0      OS
4      104.0    Alice        3.0     TOC
5        NaN      NaN        4.0    DBMS

In [94]:

outer_join = pd.merge(students, subjects, on='SubjectID', how='outer')
outer_join

   StudentID     Name  SubjectID SubName
0      101.0     John        1.0      AI
1      103.0      Bob        1.0      AI
2      102.0     Jane        2.0      OS
3      105.0  Charlie        2.0      OS
4      104.0    Alice        3.0     TOC
5        NaN      NaN        4.0    DBMS
6      106.0    Henry        NaN     NaN

In [95]:
merged = students.merge(subjects, on='SubjectID').merge(marks, on='StudentID')
merged

   StudentID     Name  SubjectID SubName  marks
0        101     John        1.0      AI     60
1        102     Jane        2.0      OS     75
2        103      Bob        1.0      AI     55
3        104    Alice        3.0     TOC     80
4        105  Charlie        2.0      OS     70

# concatenation

In [101]:
df1 = pd.DataFrame({
    "ID": [1, 2],
    "Name": ["Anita", "Alice"]
})

df2 = pd.DataFrame({
    "ID": [3, 4],
    "Name": ["Bibek", "Rahul"]
})

In [102]:
result = pd.concat([df1, df2])

In [103]:
result

   ID   Name
0   1  Anita
1   2  Alice
0   3  Bibek
1   4  Rahul

In [104]:
result = pd.concat([df1, df2], ignore_index = True)

In [105]:
result

   ID   Name
0   1  Anita
1   2  Alice
2   3  Bibek
3   4  Rahul