In [154]:
s = pd.Series([5, 10, 15, 20, 25])

In [155]:
print(s)

0     5
1    10
2    15
3    20
4    25
dtype: int64

In [156]:
print(type(s))

<class 'pandas.Series'>

In [159]:
print(s.index)

RangeIndex(start=0, stop=5, step=1)

In [160]:
print(s.values)

[ 5 10 15 20 25]

In [161]:
print(s.shape)

(5,)

In [162]:
s.sum()

np.int64(75)

In [163]:
print(s.hasnans)

False

In [171]:
marks = pd.Series([80, 65, 92, 70, 88])
print("maximum = ", marks.max())
print("minimum = ", marks.min())
print("average = ", marks.mean())
print("totalmarks", marks.sum())

maximum =  92
minimum =  65
average =  79.0
totalmarks 395

In [172]:
nba = pd.read_csv("nba.csv")

In [173]:
nba.head(7)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0

In [175]:
nba.tail(6)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [176]:
nba.shape

(458, 9)

In [177]:
nba.index

RangeIndex(start=0, stop=458, step=1)

In [178]:
nba.values

array([['Avery Bradley', 'Boston Celtics', 0.0, ..., 180.0, 'Texas',
        7730337.0],
       ['Jae Crowder', 'Boston Celtics', 99.0, ..., 235.0, 'Marquette',
        6796117.0],
       ['John Holland', 'Boston Celtics', 30.0, ..., 205.0,
        'Boston University', nan],
       ...,
       ['Tibor Pleiss', 'Utah Jazz', 21.0, ..., 256.0, nan, 2900000.0],
       ['Jeff Withey', 'Utah Jazz', 24.0, ..., 231.0, 'Kansas', 947276.0],
       [nan, nan, nan, ..., nan, nan, nan]], shape=(458, 9), dtype=object)

In [182]:
nba.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='str')

In [183]:
nba.dtypes

Name            str
Team            str
Number      float64
Position        str
Age         float64
Height          str
Weight      float64
College         str
Salary      float64
dtype: object

In [184]:
nba.info()

<class 'pandas.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    str
 1   Team      457 non-null    str
 2   Number    457 non-null    float64
 3   Position  457 non-null    str
 4   Age       457 non-null    float64
 5   Height    457 non-null    str
 6   Weight    457 non-null    float64
 7   College   373 non-null    str
 8   Salary    446 non-null    float64
dtypes: float64(4), str(5)
memory usage: 32.3 KB

In [188]:
nba.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [189]:
names = nba["Name"]
teams = nba["Team"]
salaries = nba["Salary"]

In [190]:
print(names)
print(teams)
print(salaries)

0      Avery Bradley
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, Length: 458, dtype: str
0      Boston Celtics
1      Boston Celtics
2      Boston Celtics
3      Boston Celtics
4      Boston Celtics
            ...
453         Utah Jazz
454         Utah Jazz
455         Utah Jazz
456         Utah Jazz
457               NaN
Name: Team, Length: 458, dtype: str
0      7730337.0
1      6796117.0
2            NaN
3      1148640.0
4      5000000.0
         ...
453    2433333.0
454     900000.0
455    2900000.0
456     947276.0
457          NaN
Name: Salary, Length: 458, dtype: float64

In [191]:
new_df = nba[['Name', 'Team', 'Position', 'Salary']]
new_df

              Name            Team Position     Salary
0    Avery Bradley  Boston Celtics       PG  7730337.0
1      Jae Crowder  Boston Celtics       SF  6796117.0
2     John Holland  Boston Celtics       SG        NaN
3      R.J. Hunter  Boston Celtics       SG  1148640.0
4    Jonas Jerebko  Boston Celtics       PF  5000000.0
..             ...             ...      ...        ...
453   Shelvin Mack       Utah Jazz       PG  2433333.0
454      Raul Neto       Utah Jazz       PG   900000.0
455   Tibor Pleiss       Utah Jazz        C  2900000.0
456    Jeff Withey       Utah Jazz        C   947276.0
457            NaN             NaN      NaN        NaN

[458 rows x 4 columns]

In [194]:
new_df = nba[['Salary', 'Age', 'Name']]
new_df

        Salary   Age           Name
0    7730337.0  25.0  Avery Bradley
1    6796117.0  25.0    Jae Crowder
2          NaN  27.0   John Holland
3    1148640.0  22.0    R.J. Hunter
4    5000000.0  29.0  Jonas Jerebko
..         ...   ...            ...
453  2433333.0  26.0   Shelvin Mack
454   900000.0  24.0      Raul Neto
455  2900000.0  26.0   Tibor Pleiss
456   947276.0  26.0    Jeff Withey
457        NaN   NaN            NaN

[458 rows x 3 columns]

In [195]:
nba["Team"].value_counts()

Team
New Orleans Pelicans      19
Memphis Grizzlies         18
New York Knicks           16
Milwaukee Bucks           16
Boston Celtics            15
Brooklyn Nets             15
Philadelphia 76ers        15
Toronto Raptors           15
Golden State Warriors     15
Los Angeles Clippers      15
Los Angeles Lakers        15
Phoenix Suns              15
Sacramento Kings          15
Chicago Bulls             15
Cleveland Cavaliers       15
Detroit Pistons           15
Indiana Pacers            15
Dallas Mavericks          15
Houston Rockets           15
San Antonio Spurs         15
Atlanta Hawks             15
Charlotte Hornets         15
Miami Heat                15
Washington Wizards        15
Denver Nuggets            15
Oklahoma City Thunder     15
Portland Trail Blazers    15
Utah Jazz                 15
Orlando Magic             14
Minnesota Timberwolves    14
Name: count, dtype: int64

In [196]:
nba["Position"].value_counts()

Position
SG    102
PF    100
PG     92
SF     85
C      78
Name: count, dtype: int64

In [199]:
nba["Position"].value_counts(normalize = True) * 100

Position
SG    22.319475
PF    21.881838
PG    20.131291
SF    18.599562
C     17.067834
Name: proportion, dtype: float64

In [201]:
(nba["Position"].value_counts(normalize = True) * 100).sum()

np.float64(100.00000000000001)

In [202]:
nba["College"]

0                  Texas
1              Marquette
2      Boston University
3          Georgia State
4                    NaN
             ...
453               Butler
454                  NaN
455                  NaN
456               Kansas
457                  NaN
Name: College, Length: 458, dtype: str

In [203]:
nba["College"].nunique()

118

In [205]:
print(nba["Position"].unique())

<StringArray>
['PG', 'SF', 'SG', 'PF', 'C', nan]
Length: 6, dtype: str

In [206]:
nba["Sport"] = "Basketball"

In [207]:
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Sport
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,Basketball
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,Basketball
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,Basketball
...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,Basketball
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,Basketball
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,Basketball
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,Basketball
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Basketball

In [208]:
nba["Triple_salary"] = nba["Salary"] * 3

In [209]:
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Sport,Triple_salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball,23191011.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball,20388351.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,Basketball,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,Basketball,3445920.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,Basketball,15000000.0
...,...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,Basketball,7299999.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,Basketball,2700000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,Basketball,8700000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,Basketball,2841828.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Basketball,NaN

In [210]:
nba["Salary Bonus"] = nba["Salary"] + 250000

In [211]:
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Sport,Triple_salary,Salary Bonus
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball,23191011.0,7980337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball,20388351.0,7046117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,Basketball,NaN,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,Basketball,3445920.0,1398640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,Basketball,15000000.0,5250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,Basketball,7299999.0,2683333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,Basketball,2700000.0,1150000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,Basketball,8700000.0,3150000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,Basketball,2841828.0,1197276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Basketball,NaN,NaN

In [213]:
nba["Position Full Name"] = nba["Position"].map({
    "PG" : "Point Guard",
    "SG" : "Shooting Guard",
    "SF" : "Small Forward",
    "PF" : "Power Forward",
    "C" : "Center"
})

In [214]:
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Sport,Triple_salary,Salary Bonus,Position Full Name
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball,23191011.0,7980337.0,Point Guard
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball,20388351.0,7046117.0,Small Forward
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,Basketball,NaN,NaN,Shooting Guard
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,Basketball,3445920.0,1398640.0,Shooting Guard
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,Basketball,15000000.0,5250000.0,Power Forward
...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,Basketball,7299999.0,2683333.0,Point Guard
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,Basketball,2700000.0,1150000.0,Point Guard
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,Basketball,8700000.0,3150000.0,Center
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,Basketball,2841828.0,1197276.0,Center
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Basketball,NaN,NaN,NaN

In [216]:
revenue = pd.read_csv("revenue.csv", index_col = "Date")

In [217]:
revenue

         New York  Los Angeles  Miami
Date
1/1/16        985          122    499
1/2/16        738          788    534
1/3/16         14           20    933
1/4/16        730          904    885
1/5/16        114           71    253
1/6/16        936          502    497
1/7/16        123          996    115
1/8/16        935          492    886
1/9/16        846          954    823
1/10/16        54          285    216

In [218]:
revenue.reset_index()

      Date  New York  Los Angeles  Miami
0   1/1/16       985          122    499
1   1/2/16       738          788    534
2   1/3/16        14           20    933
3   1/4/16       730          904    885
4   1/5/16       114           71    253
5   1/6/16       936          502    497
6   1/7/16       123          996    115
7   1/8/16       935          492    886
8   1/9/16       846          954    823
9  1/10/16        54          285    216

In [219]:
revenue

         New York  Los Angeles  Miami
Date
1/1/16        985          122    499
1/2/16        738          788    534
1/3/16         14           20    933
1/4/16        730          904    885
1/5/16        114           71    253
1/6/16        936          502    497
1/7/16        123          996    115
1/8/16        935          492    886
1/9/16        846          954    823
1/10/16        54          285    216

In [220]:
revenue.reset_index(inplace= True)
revenue

      Date  New York  Los Angeles  Miami
0   1/1/16       985          122    499
1   1/2/16       738          788    534
2   1/3/16        14           20    933
3   1/4/16       730          904    885
4   1/5/16       114           71    253
5   1/6/16       936          502    497
6   1/7/16       123          996    115
7   1/8/16       935          492    886
8   1/9/16       846          954    823
9  1/10/16        54          285    216

In [226]:
revenue.set_index("Date", inplace = True)

In [223]:
revenue

         New York  Los Angeles  Miami
Date
1/1/16        985          122    499
1/2/16        738          788    534
1/3/16         14           20    933
1/4/16        730          904    885
1/5/16        114           71    253
1/6/16        936          502    497
1/7/16        123          996    115
1/8/16        935          492    886
1/9/16        846          954    823
1/10/16        54          285    216

In [228]:
print("Sum of every city: ")
revenue.sum(axis = 0)

Sum of every city:

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

In [229]:
print("Sum of every city: ")
revenue.sum(axis = 1)

Sum of every city:

Date
1/1/16     1606
1/2/16     2060
1/3/16      967
1/4/16     2519
1/5/16      438
1/6/16     1935
1/7/16     1234
1/8/16     2313
1/9/16     2623
1/10/16     555
dtype: int64

In [230]:
revenue.sum(axis = 1).sum()

np.int64(16250)

In [231]:
nba = pd.read_csv("nba.csv")

In [232]:
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [234]:
nba.duplicated(keep = False).sum()

np.int64(0)

In [236]:
nba["Sport"] = "Baseketball"

In [237]:
columns = [
    "Team",
    "Position",
    "Sport",
    "Height",
    "College"
]
new_df = nba[columns]

In [239]:
new_df.duplicated(keep = False).sum()

np.int64(12)

In [240]:
new_df[new_df.duplicated(keep = False)]

                   Team Position        Sport Height         College
68      Toronto Raptors        C  Baseketball    7-0             NaN
74      Toronto Raptors        C  Baseketball    7-0             NaN
155       Chicago Bulls       PF  Baseketball   6-10             NaN
160       Chicago Bulls       PF  Baseketball   6-10             NaN
327   Charlotte Hornets       PF  Baseketball    6-9  North Carolina
337   Charlotte Hornets       PF  Baseketball    6-9  North Carolina
354       Orlando Magic        C  Baseketball    7-0             USC
366       Orlando Magic        C  Baseketball    7-0             USC
372  Washington Wizards       PF  Baseketball   6-10          Kansas
373  Washington Wizards        C  Baseketball   6-11             NaN
375  Washington Wizards        C  Baseketball   6-11             NaN
376  Washington Wizards       PF  Baseketball   6-10          Kansas

In [ ]:
# keep = 'first ' is default as it says keep the first occurence row and do n't show it as a duplicated row
# keep = 'last ' it says keep the last occurence row and do n't show it as a duplicated row
# keep = False  it says shows all duplicated rows

In [241]:
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Sport
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,Baseketball
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,Baseketball
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,Baseketball
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,Baseketball
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,Baseketball
...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,Baseketball
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,Baseketball
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,Baseketball
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,Baseketball
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Baseketball