# DataFrames I

In [ ]:
https://github.com/laxmimerit/All-CSV-ML-Data-Files-Download/blob/master/revenue.csv

In [2]:
import pandas as pd

## Methods and Attributes between Series and DataFrames
- A **DataFrame** is a 2-dimensional table consisting of rows and columns.
- Pandas uses a `NaN` designation for cells that have a missing value. It is short for "not a number". Most operations on `NaN` values will produce `NaN` values.
- Like with a **Series**, Pandas assigns an index position/label to each **DataFrame** row.
- The **DataFrame** and **Series** have common and exclusive methods/attributes.
- The `hasnans` attribute exists only a **Series**. The `columns` attribute exists only on a **DataFrame**.
- Some methods/attributes will return different types of data.
- The `info` method returns a summary of the pandas object.

In [3]:
nba = pd.read_csv("nba.csv")
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
s = pd.Series([1, 2, 3, 4, 5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
nba.head()
nba.head(n=5)
nba.head(8)

nba.tail()
nba.tail(n=7)
nba.tail(1)

    Name Team  Number Position  Age Height  Weight College  Salary
457  NaN  NaN     NaN      NaN  NaN    NaN     NaN     NaN     NaN

In [6]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
nba.index

RangeIndex(start=0, stop=458, step=1)

In [8]:
s.values

array([1, 2, 3, 4, 5])

In [9]:
nba.values

array([['Avery Bradley', 'Boston Celtics', 0.0, ..., 180.0, 'Texas',
        7730337.0],
       ['Jae Crowder', 'Boston Celtics', 99.0, ..., 235.0, 'Marquette',
        6796117.0],
       ['John Holland', 'Boston Celtics', 30.0, ..., 205.0,
        'Boston University', nan],
       ...,
       ['Tibor Pleiss', 'Utah Jazz', 21.0, ..., 256.0, nan, 2900000.0],
       ['Jeff Withey', 'Utah Jazz', 24.0, ..., 231.0, 'Kansas', 947276.0],
       [nan, nan, nan, ..., nan, nan, nan]], shape=(458, 9), dtype=object)

In [10]:
# represent the list of columns
nba.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='str')

In [11]:
# datatypes of series
s.dtypes

dtype('int64')

In [13]:
# datatypes of dataframe
nba.dtypes
# we may need to change the datatype of height and other columns whose datatypes should be different if we will use that column in future

Name            str
Team            str
Number      float64
Position        str
Age         float64
Height          str
Weight      float64
College         str
Salary      float64
dtype: object

In [14]:
s.shape
nba.shape

(458, 9)

In [15]:
s.dtypes
nba.dtypes

Name            str
Team            str
Number      float64
Position        str
Age         float64
Height          str
Weight      float64
College         str
Salary      float64
dtype: object

In [16]:
s.hasnans # shows whether there is nan value but only available in series
# nba.hasnans

False

In [17]:
nba.columns
#s.columns # columns is not available in series

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='str')

In [18]:
# s.axes
nba.axes

[RangeIndex(start=0, stop=458, step=1),
 Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
        'College', 'Salary'],
       dtype='str')]

In [19]:
# info() gives us the information about non-null values and many more
s.info()

<class 'pandas.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

In [20]:
nba.info()

<class 'pandas.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    str
 1   Team      457 non-null    str
 2   Number    457 non-null    float64
 3   Position  457 non-null    str
 4   Age       457 non-null    float64
 5   Height    457 non-null    str
 6   Weight    457 non-null    float64
 7   College   373 non-null    str
 8   Salary    446 non-null    float64
dtypes: float64(4), str(5)
memory usage: 32.3 KB

In [28]:
nba.tail()
# at first we should take each column and find out how many unique values are there which helps to find the duplicates values
# then we need to use value_counts to find out the frequency of those unique values
# we can check the null values as well

# in the below table height column has datatype str as it contains "-" so we can replace it with . to convert its datatype to float

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

5.7

## Differences between Shared Methods
- The `sum` method adds a **Series's** values.
- On a **DataFrame**, the `sum` method defaults to adding the values by traversing the index (row values).
- The `axis` parameter customizes the direction that we add across. Pass `"columns"` or `1` to add "across" the columns.

In [34]:
# creating dataframe
data = {
    "Date": [
        "1/1/16", "1/2/16", "1/3/16", "1/4/16", "1/5/16",
        "1/6/16", "1/7/16", "1/8/16", "1/9/16", "1/10/16"
    ],
    "New York": [985, 738, 14, 730, 114, 936, 123, 935, 846, 54],
    "Los Angeles": [122, 788, 20, 904, 71, 502, 996, 492, 954, 285],
    "Miami": [499, 534, 933, 885, 253, 497, 115, 886, 823, 216]
}

df = pd.DataFrame(data)
df.to_csv("revenue.csv") # by default while converting the dataframe to csv then index is inserted and if we don't want the index then pass index = False to to_csv method

In [35]:
#there are two index - one created during conversion to csv and another while reading csv file
revenue = pd.read_csv("revenue.csv")
revenue

   Unnamed: 0     Date  New York  Los Angeles  Miami
0           0   1/1/16       985          122    499
1           1   1/2/16       738          788    534
2           2   1/3/16        14           20    933
3           3   1/4/16       730          904    885
4           4   1/5/16       114           71    253
5           5   1/6/16       936          502    497
6           6   1/7/16       123          996    115
7           7   1/8/16       935          492    886
8           8   1/9/16       846          954    823
9           9  1/10/16        54          285    216

In [37]:
# creating dataframe while passing index = False to remove the default index while conversion
data = {
    "Date": [
        "1/1/16", "1/2/16", "1/3/16", "1/4/16", "1/5/16",
        "1/6/16", "1/7/16", "1/8/16", "1/9/16", "1/10/16"
    ],
    "New York": [985, 738, 14, 730, 114, 936, 123, 935, 846, 54],
    "Los Angeles": [122, 788, 20, 904, 71, 502, 996, 492, 954, 285],
    "Miami": [499, 534, 933, 885, 253, 497, 115, 886, 823, 216]
}

df = pd.DataFrame(data)
df.to_csv("revenue.csv", index = False)

In [40]:
# now only one index comes
revenue = pd.read_csv("revenue.csv",)
revenue

      Date  New York  Los Angeles  Miami
0   1/1/16       985          122    499
1   1/2/16       738          788    534
2   1/3/16        14           20    933
3   1/4/16       730          904    885
4   1/5/16       114           71    253
5   1/6/16       936          502    497
6   1/7/16       123          996    115
7   1/8/16       935          492    886
8   1/9/16       846          954    823
9  1/10/16        54          285    216

In [42]:
# reading csv making index using Date column
revenue = pd.read_csv("revenue.csv",index_col= "Date")
revenue

         New York  Los Angeles  Miami
Date
1/1/16        985          122    499
1/2/16        738          788    534
1/3/16         14           20    933
1/4/16        730          904    885
1/5/16        114           71    253
1/6/16        936          502    497
1/7/16        123          996    115
1/8/16        935          492    886
1/9/16        846          954    823
1/10/16        54          285    216

In [44]:
# reset_index() resets the dataframe index and the column using as index becomes one of the column
revenue = revenue.reset_index()
revenue

      Date  New York  Los Angeles  Miami
0   1/1/16       985          122    499
1   1/2/16       738          788    534
2   1/3/16        14           20    933
3   1/4/16       730          904    885
4   1/5/16       114           71    253
5   1/6/16       936          502    497
6   1/7/16       123          996    115
7   1/8/16       935          492    886
8   1/9/16       846          954    823
9  1/10/16        54          285    216

In [45]:
# set_index() sets the column to be index of the df
revenue.set_index("Date")

         New York  Los Angeles  Miami
Date
1/1/16        985          122    499
1/2/16        738          788    534
1/3/16         14           20    933
1/4/16        730          904    885
1/5/16        114           71    253
1/6/16        936          502    497
1/7/16        123          996    115
1/8/16        935          492    886
1/9/16        846          954    823
1/10/16        54          285    216

In [48]:
# revenue has not changed as we have not change the original df
revenue

      Date  New York  Los Angeles  Miami
0   1/1/16       985          122    499
1   1/2/16       738          788    534
2   1/3/16        14           20    933
3   1/4/16       730          904    885
4   1/5/16       114           71    253
5   1/6/16       936          502    497
6   1/7/16       123          996    115
7   1/8/16       935          492    886
8   1/9/16       846          954    823
9  1/10/16        54          285    216

In [ ]:
# while reading we use index_col to set one of the column as index
# after reading we use reset_index and set_index for indexing with the column

In [49]:
# if we don't want to assign the changes to the original df using "=", then use inplace=True for that 
revenue.set_index("Date", inplace = True)
revenue

         New York  Los Angeles  Miami
Date
1/1/16        985          122    499
1/2/16        738          788    534
1/3/16         14           20    933
1/4/16        730          904    885
1/5/16        114           71    253
1/6/16        936          502    497
1/7/16        123          996    115
1/8/16        935          492    886
1/9/16        846          954    823
1/10/16        54          285    216

In [15]:
revenue

         New York  Los Angeles  Miami
Date
1/1/16        985          122    499
1/2/16        738          788    534
1/3/16         14           20    933
1/4/16        730          904    885
1/5/16        114           71    253
1/6/16        936          502    497
1/7/16        123          996    115
1/8/16        935          492    886
1/9/16        846          954    823
1/10/16        54          285    216

In [50]:
s = pd.Series([1, 2, 3])
# all the following three lines does same thing
s.sum(axis="index")
s.sum(axis=0)
s.sum()

np.int64(6)

In [51]:
# this adds the values of each column of df
revenue.sum()

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

In [54]:
# revenue.sum() is a series now we can apply sum method
revenue.sum().sum()

np.int64(16250)

In [52]:
revenue.sum(axis="index")

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

In [21]:
revenue.sum(axis="columns")

Date
1/1/16     1606
1/2/16     2060
1/3/16      967
1/4/16     2519
1/5/16      438
1/6/16     1935
1/7/16     1234
1/8/16     2313
1/9/16     2623
1/10/16     555
dtype: int64

In [55]:
revenue.sum(axis="columns").sum()

np.int64(16250)

In [56]:
revenue.sum(axis="columns").sum().sum()

np.int64(16250)

In [ ]:
revenue.sum()

| Code                        | Same as                       | Meaning                   |
| --------------------------- | ----------------------------- | ------------------------- |
| `revenue.sum()`             | `revenue.sum(axis=0)`         | Sum columns (down rows)   |
| `revenue.sum(axis="index")` | `revenue.sum(axis=0)`         | Sum columns (down rows)   |
| `revenue.sum(axis=1)`       | `revenue.sum(axis="columns")` | Sum rows (across columns) |

## Select One Column from a DataFrame
- We can use attribute syntax (`df.column_name`) to select a column from a **DataFrame**. The syntax will not work if the column name has spaces.
- We can also use square bracket syntax (`df["column name"]`) which will work for any column name.
- Pandas extracts a column from a **DataFrame** as a **Series**.
- The **Series** is a view, so changes to the **Series** *will* affect the **DataFrame**.
- Pandas will display a warning if you mutate the **Series**. Use the `copy` method to create a duplicate.

In [3]:
nba = pd.read_csv("nba.csv")
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [4]:
print(nba.Team)
print(nba.Salary)
print(nba.Name)
# nba.name
type(nba.Name)

0      Boston Celtics
1      Boston Celtics
2      Boston Celtics
3      Boston Celtics
4      Boston Celtics
            ...
453         Utah Jazz
454         Utah Jazz
455         Utah Jazz
456         Utah Jazz
457               NaN
Name: Team, Length: 458, dtype: str
0      7730337.0
1      6796117.0
2            NaN
3      1148640.0
4      5000000.0
         ...
453    2433333.0
454     900000.0
455    2900000.0
456     947276.0
457          NaN
Name: Salary, Length: 458, dtype: float64
0      Avery Bradley
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, Length: 458, dtype: str

pandas.Series

In [6]:
print(nba["Team"])
print(nba["Salary"])

0      Boston Celtics
1      Boston Celtics
2      Boston Celtics
3      Boston Celtics
4      Boston Celtics
            ...
453         Utah Jazz
454         Utah Jazz
455         Utah Jazz
456         Utah Jazz
457               NaN
Name: Team, Length: 458, dtype: str
0      7730337.0
1      6796117.0
2            NaN
3      1148640.0
4      5000000.0
         ...
453    2433333.0
454     900000.0
455    2900000.0
456     947276.0
457          NaN
Name: Salary, Length: 458, dtype: float64

In [7]:
names = nba["Name"].copy()
names

0      Avery Bradley
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, Length: 458, dtype: str

In [8]:
names.iloc[0] = "Whatever"

In [9]:
names.head()

0         Whatever
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
Name: Name, dtype: str

In [10]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

## Select Multiple Columns from a DataFrame
- Use square brackets with a list of names to extract multiple **DataFrame** columns.
- Pandas stores the result in a new **DataFrame** (a copy).

In [ ]:
nba = pd.read_csv("nba.csv")
nba.head()

In [11]:
# sometimes we may need to take certain column from the dataframe and to work on it. In such cases, we can select multiple columns
nba[["Name", "Team"]]
nba[["Team", "Name"]]

nba[["Salary", "Team", "Name"]]

columns_to_select = ["Salary", "Team", "Name"]
nba[columns_to_select]

        Salary            Team           Name
0    7730337.0  Boston Celtics  Avery Bradley
1    6796117.0  Boston Celtics    Jae Crowder
2          NaN  Boston Celtics   John Holland
3    1148640.0  Boston Celtics    R.J. Hunter
4    5000000.0  Boston Celtics  Jonas Jerebko
..         ...             ...            ...
453  2433333.0       Utah Jazz   Shelvin Mack
454   900000.0       Utah Jazz      Raul Neto
455  2900000.0       Utah Jazz   Tibor Pleiss
456   947276.0       Utah Jazz    Jeff Withey
457        NaN             NaN            NaN

[458 rows x 3 columns]

## Add New Column to DataFrame
- Use square bracket extraction syntax with an equal sign to add a new **Series** to a **DataFrame**.
- The `insert` method allows us to insert an element at a specific column index.
- On the right-hand side, we can reference an existing **DataFrame** column and perform a broadcasting operation on it to create the new **Series**.

In [12]:
nba = pd.read_csv("nba.csv")
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [13]:

nba["Position"].value_counts()

Position
SG    102
PF    100
PG     92
SF     85
C      78
Name: count, dtype: int64

In [14]:
# as there is no any Sport column so this creates a new sport column at the last of the column
nba["Sport"] = "Basketball"

In [21]:
# position column may have same value as the key of the following dictionary so now those values are changed by their respective values of the following dictonary
nba["Position_Name"] = nba["Position"].map({
    "PG": "Point Guard",
    "SG": "Shooting Guard",
    "SF": "Small Forward",
    "C": "Center",
    "PF": "Power Forward"
})

In [22]:
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Sport,Position_Name
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball,Point Guard
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball,Small Forward
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,Basketball,Shooting Guard
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,Basketball,Shooting Guard
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,Basketball,Power Forward
...,...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,Basketball,Point Guard
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,Basketball,Point Guard
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,Basketball,Center
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,Basketball,Center
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Basketball,NaN

In [24]:
# insert() function takes the location and create a column there with given value
nba.insert(loc=3, column="Sports", value="Basketball")

In [25]:
nba

,Name,Team,Number,Sports,Position,Age,Height,Weight,College,Salary,Sport,Position_Name
0,Avery Bradley,Boston Celtics,0.0,Basketball,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball,Point Guard
1,Jae Crowder,Boston Celtics,99.0,Basketball,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball,Small Forward
2,John Holland,Boston Celtics,30.0,Basketball,SG,27.0,6-5,205.0,Boston University,NaN,Basketball,Shooting Guard
3,R.J. Hunter,Boston Celtics,28.0,Basketball,SG,22.0,6-5,185.0,Georgia State,1148640.0,Basketball,Shooting Guard
4,Jonas Jerebko,Boston Celtics,8.0,Basketball,PF,29.0,6-10,231.0,NaN,5000000.0,Basketball,Power Forward
...,...,...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,Basketball,PG,26.0,6-3,203.0,Butler,2433333.0,Basketball,Point Guard
454,Raul Neto,Utah Jazz,25.0,Basketball,PG,24.0,6-1,179.0,NaN,900000.0,Basketball,Point Guard
455,Tibor Pleiss,Utah Jazz,21.0,Basketball,C,26.0,7-3,256.0,NaN,2900000.0,Basketball,Center
456,Jeff Withey,Utah Jazz,24.0,Basketball,C,26.0,7-0,231.0,Kansas,947276.0,Basketball,Center
457,NaN,NaN,NaN,Basketball,NaN,NaN,NaN,NaN,NaN,NaN,Basketball,NaN

In [30]:
# manipulating the existing column and making new column which is allowed in pandas
nba["Salary"] * 2
nba["Salary"].mul(2)

nba["Salary Doubled"] = nba["Salary"].mul(2)

In [27]:
nba

,Name,Team,Number,Sports,Position,Age,Height,Weight,College,Salary,Sport,Position_Name,Salary Doubled
0,Avery Bradley,Boston Celtics,0.0,Basketball,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball,Point Guard,15460674.0
1,Jae Crowder,Boston Celtics,99.0,Basketball,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball,Small Forward,13592234.0
2,John Holland,Boston Celtics,30.0,Basketball,SG,27.0,6-5,205.0,Boston University,NaN,Basketball,Shooting Guard,NaN
3,R.J. Hunter,Boston Celtics,28.0,Basketball,SG,22.0,6-5,185.0,Georgia State,1148640.0,Basketball,Shooting Guard,2297280.0
4,Jonas Jerebko,Boston Celtics,8.0,Basketball,PF,29.0,6-10,231.0,NaN,5000000.0,Basketball,Power Forward,10000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,Basketball,PG,26.0,6-3,203.0,Butler,2433333.0,Basketball,Point Guard,4866666.0
454,Raul Neto,Utah Jazz,25.0,Basketball,PG,24.0,6-1,179.0,NaN,900000.0,Basketball,Point Guard,1800000.0
455,Tibor Pleiss,Utah Jazz,21.0,Basketball,C,26.0,7-3,256.0,NaN,2900000.0,Basketball,Center,5800000.0
456,Jeff Withey,Utah Jazz,24.0,Basketball,C,26.0,7-0,231.0,Kansas,947276.0,Basketball,Center,1894552.0
457,NaN,NaN,NaN,Basketball,NaN,NaN,NaN,NaN,NaN,NaN,Basketball,NaN,NaN

In [28]:
nba["Salary"] - 500000
nba["Salary"].sub(500000)

nba["New SalarySub"] = nba["Salary"].sub(500000)

In [29]:
nba

,Name,Team,Number,Sports,Position,Age,Height,Weight,College,Salary,Sport,Position_Name,Salary Doubled,New SalarySub
0,Avery Bradley,Boston Celtics,0.0,Basketball,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball,Point Guard,15460674.0,7230337.0
1,Jae Crowder,Boston Celtics,99.0,Basketball,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball,Small Forward,13592234.0,6296117.0
2,John Holland,Boston Celtics,30.0,Basketball,SG,27.0,6-5,205.0,Boston University,NaN,Basketball,Shooting Guard,NaN,NaN
3,R.J. Hunter,Boston Celtics,28.0,Basketball,SG,22.0,6-5,185.0,Georgia State,1148640.0,Basketball,Shooting Guard,2297280.0,648640.0
4,Jonas Jerebko,Boston Celtics,8.0,Basketball,PF,29.0,6-10,231.0,NaN,5000000.0,Basketball,Power Forward,10000000.0,4500000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,Basketball,PG,26.0,6-3,203.0,Butler,2433333.0,Basketball,Point Guard,4866666.0,1933333.0
454,Raul Neto,Utah Jazz,25.0,Basketball,PG,24.0,6-1,179.0,NaN,900000.0,Basketball,Point Guard,1800000.0,400000.0
455,Tibor Pleiss,Utah Jazz,21.0,Basketball,C,26.0,7-3,256.0,NaN,2900000.0,Basketball,Center,5800000.0,2400000.0
456,Jeff Withey,Utah Jazz,24.0,Basketball,C,26.0,7-0,231.0,Kansas,947276.0,Basketball,Center,1894552.0,447276.0
457,NaN,NaN,NaN,Basketball,NaN,NaN,NaN,NaN,NaN,NaN,Basketball,NaN,NaN,NaN

In [ ]:
# mostly things done in pandas-
# how many unique values are there in each column 
# how many duplicate rows are there 
# how many duplicate values are there

## A Review of the value_counts Method
- The `value_counts` method counts the number of times that each unique value occurs in a **Series**.

In [ ]:
# nba = pd.read_csv("nba.csv")
# nba.head()

In [ ]:
# at first we find out how many unique values are there using unique method 
# and then value_counts gives us those unique and their frequency

In [31]:
nba["Team"].value_counts()

Team
New Orleans Pelicans      19
Memphis Grizzlies         18
New York Knicks           16
Milwaukee Bucks           16
Boston Celtics            15
Brooklyn Nets             15
Philadelphia 76ers        15
Toronto Raptors           15
Golden State Warriors     15
Los Angeles Clippers      15
Los Angeles Lakers        15
Phoenix Suns              15
Sacramento Kings          15
Chicago Bulls             15
Cleveland Cavaliers       15
Detroit Pistons           15
Indiana Pacers            15
Dallas Mavericks          15
Houston Rockets           15
San Antonio Spurs         15
Atlanta Hawks             15
Charlotte Hornets         15
Miami Heat                15
Washington Wizards        15
Denver Nuggets            15
Oklahoma City Thunder     15
Portland Trail Blazers    15
Utah Jazz                 15
Orlando Magic             14
Minnesota Timberwolves    14
Name: count, dtype: int64

In [32]:
nba["Position"].value_counts()

Position
SG    102
PF    100
PG     92
SF     85
C      78
Name: count, dtype: int64

In [33]:
nba["Position"].value_counts(normalize=True)

Position
SG    0.223195
PF    0.218818
PG    0.201313
SF    0.185996
C     0.170678
Name: proportion, dtype: float64

In [34]:
nba["Position"].value_counts(normalize=True) * 100

Position
SG    22.319475
PF    21.881838
PG    20.131291
SF    18.599562
C     17.067834
Name: proportion, dtype: float64

In [35]:
nba["Salary"].value_counts()

Salary
947276.0     31
845059.0     18
525093.0     13
981348.0      6
5000000.0     5
             ..
1348440.0     1
2050000.0     1
2239800.0     1
2433333.0     1
900000.0      1
Name: count, Length: 309, dtype: int64

In [36]:
dir(nba)

['Age',
 'College',
 'Height',
 'Name',
 'Number',
 'Position',
 'Position_Name',
 'Salary',
 'Sport',
 'Sports',
 'T',
 'Team',
 'Weight',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_arith_method_with_reindex',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_module_source',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_sanitize_column',
 '_select_dtypes_indices',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'between_time',
 'bfill',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_hdf',
 'to_html',
 'to_iceberg',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [37]:
# Duplicates value occurs when more than two rows have same data each and every
# we can use duplicated method
# and applying sum function to it gives us the duplicated value 
# to remove duplicate we can use drop_duplicates method and passing last , first value to the argument keep keeps the last , first row value in the df respectively

In [69]:
# practice
df = {
    "name":["Sarita", "saru", "Sarita","Sarita","saru"],
    "class" : [5,6,5,5,6]
}
df = pd.DataFrame(df)

In [70]:
df

     name  class
0  Sarita      5
1    saru      6
2  Sarita      5
3  Sarita      5
4    saru      6

In [71]:
df.duplicated()

0    False
1    False
2     True
3     True
4     True
dtype: bool

In [79]:
print("Duplicated value",df.duplicated().sum())

Duplicated value 3

In [45]:
# keeps the first value and deletes the lower duplicated rows
print("Deleting duplicates")
df.drop_duplicates()

Deleting duplicates

     name  class
0  Sarita      5
1    saru      6

In [46]:
df = {
    "name":["Sarita", "saru", "Sarita"],
    "class" : [5,6,5]
}
df = pd.DataFrame(df)

In [47]:
df.duplicated()

0    False
1    False
2     True
dtype: bool

In [49]:
# it keeps the last row
df.drop_duplicates(keep="last")

     name  class
1    saru      6
2  Sarita      5

In [50]:
nba

,Name,Team,Number,Sports,Position,Age,Height,Weight,College,Salary,Sport,Position_Name,Salary Doubled,New SalarySub
0,Avery Bradley,Boston Celtics,0.0,Basketball,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball,Point Guard,15460674.0,7230337.0
1,Jae Crowder,Boston Celtics,99.0,Basketball,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball,Small Forward,13592234.0,6296117.0
2,John Holland,Boston Celtics,30.0,Basketball,SG,27.0,6-5,205.0,Boston University,NaN,Basketball,Shooting Guard,NaN,NaN
3,R.J. Hunter,Boston Celtics,28.0,Basketball,SG,22.0,6-5,185.0,Georgia State,1148640.0,Basketball,Shooting Guard,2297280.0,648640.0
4,Jonas Jerebko,Boston Celtics,8.0,Basketball,PF,29.0,6-10,231.0,NaN,5000000.0,Basketball,Power Forward,10000000.0,4500000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,Basketball,PG,26.0,6-3,203.0,Butler,2433333.0,Basketball,Point Guard,4866666.0,1933333.0
454,Raul Neto,Utah Jazz,25.0,Basketball,PG,24.0,6-1,179.0,NaN,900000.0,Basketball,Point Guard,1800000.0,400000.0
455,Tibor Pleiss,Utah Jazz,21.0,Basketball,C,26.0,7-3,256.0,NaN,2900000.0,Basketball,Center,5800000.0,2400000.0
456,Jeff Withey,Utah Jazz,24.0,Basketball,C,26.0,7-0,231.0,Kansas,947276.0,Basketball,Center,1894552.0,447276.0
457,NaN,NaN,NaN,Basketball,NaN,NaN,NaN,NaN,NaN,NaN,Basketball,NaN,NaN,NaN

In [52]:
print("Unique values of name = ",nba["Name"].unique())
print("No. of unique name = ", nba["Name"].nunique())

Unique values of name =  <StringArray>
[ 'Avery Bradley',    'Jae Crowder',   'John Holland',    'R.J. Hunter',
  'Jonas Jerebko',   'Amir Johnson',  'Jordan Mickey',   'Kelly Olynyk',
   'Terry Rozier',   'Marcus Smart',
 ...
 'Gordon Hayward',    'Rodney Hood',     'Joe Ingles',  'Chris Johnson',
     'Trey Lyles',   'Shelvin Mack',      'Raul Neto',   'Tibor Pleiss',
    'Jeff Withey',              nan]
Length: 458, dtype: str
No. of unique name =  457

In [56]:
#taking columns to create duplicates in the multiple rows
columns_to_select = ['Team', 'Position', 'Sport', 'Height', 'College']
new_df = nba[columns_to_select]
new_df.head()

             Team Position       Sport Height            College
0  Boston Celtics       PG  Basketball    6-2              Texas
1  Boston Celtics       SF  Basketball    6-6          Marquette
2  Boston Celtics       SG  Basketball    6-5  Boston University
3  Boston Celtics       SG  Basketball    6-5      Georgia State
4  Boston Celtics       PF  Basketball   6-10                NaN

In [60]:
print("Duplicated rows:")
print(new_df.duplicated().sum())

Duplicated rows:
6

In [76]:
# TO SHOW THE DUPLICATED ROWS
new_df[new_df.duplicated(keep = False)]

                   Team Position       Sport Height         College
68      Toronto Raptors        C  Basketball    7-0             NaN
74      Toronto Raptors        C  Basketball    7-0             NaN
155       Chicago Bulls       PF  Basketball   6-10             NaN
160       Chicago Bulls       PF  Basketball   6-10             NaN
327   Charlotte Hornets       PF  Basketball    6-9  North Carolina
337   Charlotte Hornets       PF  Basketball    6-9  North Carolina
354       Orlando Magic        C  Basketball    7-0             USC
366       Orlando Magic        C  Basketball    7-0             USC
372  Washington Wizards       PF  Basketball   6-10          Kansas
373  Washington Wizards        C  Basketball   6-11             NaN
375  Washington Wizards        C  Basketball   6-11             NaN
376  Washington Wizards       PF  Basketball   6-10          Kansas

new_df[new_df.duplicated(keep = "last")]duplicated() → Returns a Boolean Series indicating duplicate rows.
Default keep='first' → First occurrence is False, later duplicates are True.
keep='last' → Last occurrence is False, earlier duplicates are True.
keep=False → Marks all rows in duplicate groups as True.
.sum() on the Boolean Series counts True values because True = 1 and False = 0.
df[df.duplicated(...)] → Uses Boole

duplicated() → Returns a Boolean Series indicating duplicate rows.

Default keep='first' → First occurrence is False, later duplicates are True.

keep='last' → Last occurrence is False, earlier duplicates are True.

keep=False → Marks all rows in duplicate groups as True.

.sum() on the Boolean Series counts True values because True = 1 and False = 0.

df[df.duplicated(...)] → Uses Boolean Indexing to display only the rows marked True.

In [94]:
# Want to know which rows belong to which group?
duplicates = new_df[new_df.duplicated(keep=False)]
print(duplicates)
# print(duplicates.groupby(list(duplicates.columns))) - LEFT

                   Team Position       Sport Height         College
68      Toronto Raptors        C  Basketball    7-0             NaN
74      Toronto Raptors        C  Basketball    7-0             NaN
155       Chicago Bulls       PF  Basketball   6-10             NaN
160       Chicago Bulls       PF  Basketball   6-10             NaN
327   Charlotte Hornets       PF  Basketball    6-9  North Carolina
337   Charlotte Hornets       PF  Basketball    6-9  North Carolina
354       Orlando Magic        C  Basketball    7-0             USC
366       Orlando Magic        C  Basketball    7-0             USC
372  Washington Wizards       PF  Basketball   6-10          Kansas
373  Washington Wizards        C  Basketball   6-11             NaN
375  Washington Wizards        C  Basketball   6-11             NaN
376  Washington Wizards       PF  Basketball   6-10          Kansas

In [93]:
# Want to count each duplicate group?
# new_df.groupby(list(duplicates.columns)).size()

## Drop Rows with Missing Values
- Pandas uses a `NaN` designation for cells that have a missing value.
- The `dropna` method deletes rows with missing values. Its default behavior is to remove a row if it has *any* missing values.
- Pass the `how` parameter an argument of "all" to delete rows where all the values are `NaN`.
- The `subset` parameters customizes/limits the columns that pandas will use to drop rows with missing values.

In [ ]:
nba = pd.read_csv("nba.csv")
nba

In [ ]:
nba.dropna()
nba.dropna(how="any")

nba.dropna(how="all")

nba.dropna(subset=["College"])
nba.dropna(subset=["College", "Salary"])

## Fill in Missing Values with the fillna Method
- The `fillna` method replaces missing `NaN` values with its argument.
- The `fillna` method is available on both **DataFrames** and **Series**.
- An extracted **Series** is a view on the original **DataFrame**, but the `fillna` method returns a copy.

In [ ]:
nba = pd.read_csv("nba.csv").dropna(how="all")
nba

In [ ]:
nba.fillna(0)

nba["Salary"] = nba["Salary"].fillna(0)

In [ ]:
nba

In [ ]:
nba["College"] = nba["College"].fillna(value="Unknown")

In [ ]:
nba

## The astype Method I
- The `astype` method converts a **Series's** values to a specified type.
- Pass in the specified type as either a string or the core Python data type.
- Pandas cannot convert `NaN` values to numeric types, so we need to eliminate/replace them before we perform the conversion.
- The `dtypes` attribute returns a **Series** with the **DataFrame's** columns and their types.

In [ ]:
nba = pd.read_csv("nba.csv").dropna(how="all")
nba["Salary"] = nba["Salary"].fillna(0)
nba["Weight"] = nba["Weight"].fillna(0)
nba

In [ ]:
nba.dtypes

In [ ]:
nba["Salary"].astype("int")
nba["Salary"].astype(int)

nba["Salary"] = nba["Salary"].astype(int)

In [ ]:
nba["Weight"] = nba["Weight"].astype(int)

In [ ]:
nba

## The astype Method II
- The `category` type is ideal for columns with a limited number of unique values.
- The `nunique` method will return a **Series** with the number of unique values in each column.
- With categories, pandas does not create a separate value in memory for each "cell". Rather, the cells point to a single copy for each unique value.

In [ ]:
nba = pd.read_csv("nba.csv").dropna(how ="all")
nba.tail()

In [ ]:
nba["Team"].nunique()
nba.nunique()

In [ ]:
nba.info()

In [ ]:
nba["Position"] = nba["Position"].astype("category")

In [ ]:
nba["Team"] = nba["Team"].astype("category")

## Sort a DataFrame with the sort_values Method I
- The `sort_values` method sorts a **DataFrame** by the values in one or more columns. The default sort is an ascending one (alphabetical for strings).
- The first parameter (`by`) expects the column(s) to sort by.
- If sorting by a single column, pass a string with its name.
- The `ascending` parameter customizes the sort order.
- The `na_position` parameter customizes where pandas places `NaN` values.

In [ ]:
nba = pd.read_csv("nba.csv")
nba.tail()

In [ ]:
nba.sort_values("Name")
nba.sort_values(by="Name")
nba.sort_values(by="Name", ascending=True)
nba.sort_values(by="Name", ascending=False)

nba.sort_values("Salary")
nba.sort_values("Salary", ascending=False)
nba.sort_values("Salary", na_position="last")
nba.sort_values("Salary", na_position="first")
nba.sort_values("Salary", na_position="first", ascending=False)

## Sort a DataFrame with the sort_values Method II
- To sort by multiple columns, pass the `by` parameter a list of column names. Pandas will sort in the specified column order (first to last).
- Pass the `ascending` parameter a Boolean to sort all columns in a consistent order (all ascending or all descending).
- Pass `ascending` a list to customize the sort order *per* column. The `ascending` list length must match the `by` list.

In [ ]:
nba = pd.read_csv("nba.csv")
nba.tail()

In [ ]:
nba.sort_values(["Team", "Name"])
nba.sort_values(by=["Team", "Name"])
nba.sort_values(by=["Team", "Name"], ascending=True)
nba.sort_values(by=["Team", "Name"], ascending=False)

nba.sort_values(by=["Team", "Name"], ascending=[True, False])

nba.sort_values(["Position", "Salary"])
nba.sort_values(["Position", "Salary"], ascending=True)
nba.sort_values(["Position", "Salary"], ascending=False)
nba.sort_values(["Position", "Salary"], ascending=[True, False])
nba.sort_values(["Position", "Salary"], ascending=[False, True])

nba = nba.sort_values(["Position", "Salary"], ascending=[False, True])
nba

## Sort a DataFrame by its Index
- The `sort_index` method sorts the **DataFrame** by its index positions/labels.

In [ ]:
nba = pd.read_csv("nba.csv")
nba = nba.sort_values(["Team", "Name"])
nba

In [ ]:
nba.sort_index()
nba.sort_index(ascending=True)
nba.sort_index(ascending=False)

nba = nba.sort_index(ascending=False)

In [ ]:
nba

## Rank Values with the rank Method
- The `rank` method assigns a numeric ranking to each **Series** value.
- Pandas will assign the same rank to equal values and create a "gap" in the dataset for the ranks.

In [ ]:
nba = pd.read_csv("nba.csv").dropna(how="all")
nba["Salary"] = nba["Salary"].fillna(0).astype(int)
nba

In [ ]:
nba["Salary"].rank()
nba["Salary"].rank(ascending=True)
nba["Salary"].rank(ascending=False).astype(int)

nba["Salary Rank"] = nba["Salary"].rank(ascending=False).astype(int)

In [ ]:
nba.sort_values("Salary", ascending=False).head(10)

In [25]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [ ]:
df = pd.Dataframe()